In [2]:
import numpy as np

In [2]:
array = np.random.randint(1,21, size = (5,5))
print(array)

[[11  3 15 13 13]
 [15 10  1 11  1]
 [ 5  7 15  7 18]
 [19 10 18 11  3]
 [ 6 20  3 15 19]]


In [3]:
array[:,2] = 1
print(array)

[[11  3  1 13 13]
 [15 10  1 11  1]
 [ 5  7  1  7 18]
 [19 10  1 11  3]
 [ 6 20  1 15 19]]


In [4]:
array = np.random.randint(1,16,size = (4,4))
print(array)

[[ 6 13  6  1]
 [13 15 14  2]
 [ 8  3 13 15]
 [ 5  3 14  3]]


In [6]:
np.fill_diagonal(array,0)
print(array)

[[ 0 13  6  1]
 [13  0 14  2]
 [ 8  3  0 15]
 [ 5  3 14  0]]


In [7]:
array = np.arange(1,37).reshape(6,6)
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [8]:
array[3:6,2:5]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [18]:
array = np.random.randint(1,25,size=(5,5))
# print(array)
border_elements = np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print(array[0,:])
print(array[-1,:])
print(array[:,0])
print(array[:,-1])
# border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print(border_elements)

[15 20 13 15 16]
[13 11 10  8 11]
[15 20  7 11 13]
[16  8 21  1 11]
[15 20 13 15 16 13 11 10  8 11 20  7 11  8 21  1]


In [19]:
arr1 = np.random.randint(1,13,size=(3,4))
arr2 = np.random.randint(1,13,size=(3,4))

#element wise operation
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[12  9 11  7]
 [10 15 19 13]
 [ 9 14  9 23]]
[[ 4 -7  9 -3]
 [ 8 -1  3  5]
 [-7 -6 -5  1]]
[[ 32   8  10  10]
 [  9  56  88  36]
 [  8  40  14 132]]
[[ 2.          0.125      10.          0.4       ]
 [ 9.          0.875       1.375       2.25      ]
 [ 0.125       0.4         0.28571429  1.09090909]]


In [ ]:
array = np.arange(1,17).reshape(4,4)
print(array)
print(np.sum(array, axis=1)) #column
print(np.sum(array, axis=0)) #row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [23]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)

[[ 9  6 20 19  6]
 [20  8  1 13 11]
 [ 3  2 17 15 10]
 [ 6 15 12 13  5]
 [ 6  6 15 10  2]]


In [25]:
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)
print(mean, median, std_dev, var)

10.0 10.0 5.642694391866354 31.84


In [3]:
matrix = np.arange(1,10).reshape(3,3)
print(np.linalg.det(matrix))
print(np.linalg.inv(matrix))
print(np.linalg.eigvals(matrix))

-9.51619735392994e-16
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
[ 1.61168440e+01 -1.11684397e+00 -4.29954797e-16]


In [ ]:
mat1 = np.random.randint(1,11,size=(2,3))
mat2 = np.random.randint(1,11,size=(3,2))
print(np.dot(mat1,mat2))

#matrix multiplication

[[84 75]
 [57 54]]


In [5]:
matrix = np.random.randint(1,10,size=(3,3))
print(matrix)
print(matrix.reshape(1,9))
print(matrix.reshape(9,1))

[[1 6 2]
 [8 1 6]
 [8 5 4]]
[[1 6 2 8 1 6 8 5 4]]
[[1]
 [6]
 [2]
 [8]
 [1]
 [6]
 [8]
 [5]
 [4]]


In [6]:
matrix = np.random.randint(1,26,size=(5,5))
print(matrix)

[[22  6 19  3  7]
 [ 2 15  3 10  6]
 [ 6  9 23  1 11]
 [12 15 19 17  4]
 [17 17  1  7  2]]


In [7]:
print(matrix.flatten())

[22  6 19  3  7  2 15  3 10  6  6  9 23  1 11 12 15 19 17  4 17 17  1  7
  2]


In [8]:
print(matrix.flatten().reshape(5,5))

[[22  6 19  3  7]
 [ 2 15  3 10  6]
 [ 6  9 23  1 11]
 [12 15 19 17  4]
 [17 17  1  7  2]]


In [9]:
matrix

array([[22,  6, 19,  3,  7],
       [ 2, 15,  3, 10,  6],
       [ 6,  9, 23,  1, 11],
       [12, 15, 19, 17,  4],
       [17, 17,  1,  7,  2]])

In [10]:
matrix[[0,0,-1,-1],[0,-1,0,-1]]

array([22,  7, 17,  2])

In [12]:
matrix = np.random.randint(1,17,size=(4,4))
print(matrix)
matrix[matrix > 10] = 10
print(matrix)

[[12  7 10 14]
 [ 5  5  8  2]
 [ 8 12  3 13]
 [ 4 11  1  7]]
[[10  7 10 10]
 [ 5  5  8  2]
 [ 8 10  3 10]
 [ 4 10  1  7]]


In [13]:
data_type = [("Name","U10"),("Age","i4"),("Weight","f4")]
data = np.array([("Alice",25,55.5),("Bob",30,85.3),("Charlie",20,65.2)],dtype=data_type)
print(data)

[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]


In [15]:
sorted_data = np.sort(data,order="Age")
print(sorted_data)

[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [31]:
data_type = [("x","i4"),("y","i4")]
data = np.array([(2,3),(4,5)], dtype = data_type)

In [32]:
data["x"]

array([2, 4], dtype=int32)

In [33]:
data["y"]

array([3, 5], dtype=int32)

In [38]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print(data["x"])

[1 3 5]


In [39]:
print(data["x"][:,np.newaxis])
print(data["x"])
print(data["y"][:,np.newaxis])
print(data["y"])

[[1]
 [3]
 [5]]
[1 3 5]
[[2]
 [4]
 [6]]
[2 4 6]


In [48]:
a = (data['x'][:,np.newaxis] - data["x"])
print(a)
print(a ** 2)

[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
[[ 0  4 16]
 [ 4  0  4]
 [16  4  0]]


In [49]:
b = (data["y"][:,np.newaxis] - data["y"])
print(b)
print(b ** 2)

[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
[[ 0  4 16]
 [ 4  0  4]
 [16  4  0]]


In [50]:
np.sqrt(a**2+b**2)

array([[0.        , 2.82842712, 5.65685425],
       [2.82842712, 0.        , 2.82842712],
       [5.65685425, 2.82842712, 0.        ]])

In [47]:
data

array([(1, 2), (3, 4), (5, 6)], dtype=[('x', '<i4'), ('y', '<i4')])

In [52]:
import numpy.ma as ma

array = np.random.randint(1,17,size=(4,4))
masked_array = ma.masked_greater(array,10)
print(array)
print(masked_array)

sum_unmasked = masked_array.sum()
print(sum_unmasked)

[[10  4 10 10]
 [14  3 16 12]
 [12  9 10  7]
 [ 1 14  7  1]]
[[10 4 10 10]
 [-- 3 -- --]
 [-- 9 10 7]
 [1 -- 7 1]]
72


In [53]:
array = np.random.randint(1,10,size=(3,3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print(array)
print(masked_array)

[[4 7 4]
 [7 3 5]
 [8 1 6]]
[[-- 7 4]
 [7 -- 5]
 [8 1 --]]


In [54]:
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print(masked_array)

[[5 7 4]
 [7 5 5]
 [8 1 5]]
